const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const { difficultyToDb } = require('../src/lib/difficulty');

const prisma = new PrismaClient();

const TEST_PASSWORD = 'sazon123';

// 'sofia' y 'marco' se resuelven al id real una vez creados los usuarios
const RECIPES = [
  {
    author: 'sofia',
    title: 'Panqueques de Avena',
    description: 'Panqueques esponjosos y saludables hechos con avena y banana. Ideales para un desayuno nutritivo sin harinas refinadas.',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
    category: 'Desayuno', difficulty: 'Fácil', cookTime: '20 min', servings: 4,
    rating: 4.8, reviewCount: 342,
    tags: ['desayuno', 'saludable', 'avena', 'panqueques', 'sin gluten'],
    ingredients: [
      { name: 'Avena', amount: '1 taza' },
      { name: 'Banana madura', amount: '1 grande' },
      { name: 'Huevos', amount: '2 unidades' },
      { name: 'Leche', amount: '½ taza' },
      { name: 'Esencia de vainilla', amount: '1 cdta' },
      { name: 'Canela', amount: '½ cdta' },
      { name: 'Sal', amount: '1 pizca' },
    ],
    steps: [
      { order: 1, description: 'Licuá la avena, banana, huevos, leche, vainilla, canela y sal hasta obtener una mezcla homogénea.' },
      { order: 2, description: 'Dejá reposar la mezcla 5 minutos mientras calentás una sartén antiadherente a fuego medio.' },
      { order: 3, description: 'Vertí ¼ taza de mezcla por panqueque. Cocinás 2-3 minutos hasta que aparezcan burbujas en la superficie.' },
      { order: 4, description: 'Dás vuelta y cocinás 1-2 minutos más. Repetís con el resto de la mezcla.' },
      { order: 5, description: 'Servís con frutas frescas, miel o mermelada.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Mousse de Chocolate',
    description: 'Un postre cremoso y decadente con solo 4 ingredientes. Perfecto para ocasiones especiales o cuando querés darte un gusto.',
    imageUrl: 'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800',
    category: 'Postre', difficulty: 'Medio', cookTime: '40 min', servings: 6,
    rating: 4.9, reviewCount: 218,
    tags: ['postre', 'chocolate', 'sin horno', 'fácil', 'mousse'],
    ingredients: [
      { name: 'Chocolate negro (70%)', amount: '200g' },
      { name: 'Crema de leche', amount: '300ml' },
      { name: 'Huevos', amount: '3 unidades' },
      { name: 'Azúcar', amount: '3 cdas' },
    ],
    steps: [
      { order: 1, description: 'Derretís el chocolate a baño maría. Dejás enfriar 5 minutos.' },
      { order: 2, description: 'Batís las yemas con el azúcar hasta blanquear. Incorporás el chocolate tibio.' },
      { order: 3, description: 'Batís las claras a nieve firme. Integrás en dos partes con movimientos envolventes.' },
      { order: 4, description: 'Batís la crema a punto chantilly e incorporás suavemente a la mezcla.' },
      { order: 5, description: 'Distribuís en copas y refrigerás mínimo 3 horas antes de servir.' },
    ],
  },
  {
    author: 'marco',
    title: 'Bowl Mediterráneo',
    description: 'Un bowl colorido y saciante con vegetales frescos, garbanzos crocantes y salsa de tahini. Vegetariano y lleno de proteínas.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    category: 'Almuerzo', difficulty: 'Fácil', cookTime: '25 min', servings: 2,
    rating: 4.7, reviewCount: 156,
    tags: ['almuerzo', 'vegetariano', 'saludable', 'bowl', 'mediterráneo'],
    ingredients: [
      { name: 'Quinoa cocida', amount: '1 taza' },
      { name: 'Garbanzos', amount: '1 lata' },
      { name: 'Pepino', amount: '1 unidad' },
      { name: 'Tomates cherry', amount: '200g' },
      { name: 'Aceitunas negras', amount: '½ taza' },
      { name: 'Tahini', amount: '3 cdas' },
      { name: 'Limón', amount: '1 unidad' },
      { name: 'Ajo', amount: '1 diente' },
    ],
    steps: [
      { order: 1, description: 'Escurrís y secás los garbanzos. Los salteás en sartén con aceite de oliva, pimentón y comino 8-10 minutos hasta dorar.' },
      { order: 2, description: 'Preparás la salsa: mezclás tahini, jugo de limón, ajo rallado y agua hasta obtener consistencia cremosa.' },
      { order: 3, description: 'Cortás el pepino en medias lunas y los tomates cherry al medio.' },
      { order: 4, description: 'Armás el bowl: base de quinoa, vegetales frescos, garbanzos crocantes y aceitunas.' },
      { order: 5, description: 'Regás con salsa de tahini y servís inmediatamente.' },
    ],
  },
  {
    author: 'marco',
    title: 'Pasta Carbonara Clásica',
    description: 'La auténtica receta romana. Sin crema, solo huevos, queso pecorino, guanciale y pimienta negra. Cremosa y perfecta.',
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    category: 'Cena', difficulty: 'Medio', cookTime: '30 min', servings: 2,
    rating: 4.9, reviewCount: 498,
    tags: ['cena', 'pasta', 'italiana', 'carbonara', 'clásica'],
    ingredients: [
      { name: 'Spaghetti', amount: '200g' },
      { name: 'Guanciale o panceta', amount: '100g' },
      { name: 'Yemas de huevo', amount: '3 unidades' },
      { name: 'Queso pecorino rallado', amount: '60g' },
      { name: 'Pimienta negra molida', amount: 'Al gusto' },
      { name: 'Sal', amount: 'Para el agua' },
    ],
    steps: [
      { order: 1, description: 'Hervís la pasta en agua con bastante sal hasta al dente. Guardás 1 taza de agua de cocción.' },
      { order: 2, description: 'Cortás el guanciale en cubos y lo cocinás en sartén fría a fuego medio hasta que suelte la grasa y quede dorado.' },
      { order: 3, description: 'Mezclás las yemas con el queso rallado y pimienta generosa hasta formar una pasta.' },
      { order: 4, description: 'Apagás el fuego, agregás la pasta a la sartén. Vertís la mezcla de huevo mezclando rápido.' },
      { order: 5, description: 'Agregás agua de cocción de a poco hasta lograr una salsa cremosa y brillante. Servís inmediatamente.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Tostada Aguacate',
    description: 'El desayuno moderno por excelencia. Pan de masa madre, palta cremosa, huevo poché y semillas. Listo en 10 minutos.',
    imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=800',
    category: 'Desayuno', difficulty: 'Fácil', cookTime: '10 min', servings: 1,
    rating: 4.5, reviewCount: 89,
    tags: ['desayuno', 'palta', 'aguacate', 'tostada', 'rápido', 'saludable'],
    ingredients: [
      { name: 'Pan de masa madre', amount: '2 rebanadas' },
      { name: 'Palta madura', amount: '1 unidad' },
      { name: 'Huevo', amount: '1 unidad' },
      { name: 'Jugo de limón', amount: '1 cdta' },
      { name: 'Semillas de sésamo', amount: '1 cdta' },
      { name: 'Hojuelas de ají', amount: 'Al gusto' },
      { name: 'Sal y pimienta', amount: 'Al gusto' },
    ],
    steps: [
      { order: 1, description: 'Tostás el pan hasta que esté dorado y crocante.' },
      { order: 2, description: 'Aplastás la palta con un tenedor, condimentás con limón, sal y pimienta.' },
      { order: 3, description: 'Poché el huevo: hervís agua con un chorrito de vinagre, creás un remolino y volcás el huevo. Cocinás 3 minutos.' },
      { order: 4, description: 'Untás la palta sobre el pan, colocás el huevo encima.' },
      { order: 5, description: 'Decorás con semillas de sésamo y hojuelas de ají. Servís de inmediato.' },
    ],
  },
  {
    author: 'marco',
    title: 'Ensalada César',
    description: 'La clásica ensalada con lechuga romana, crutones crocantes y aderezo cremoso casero. Simple y deliciosa.',
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
    category: 'Almuerzo', difficulty: 'Fácil', cookTime: '15 min', servings: 2,
    rating: 4.6, reviewCount: 201,
    tags: ['almuerzo', 'ensalada', 'clásica', 'rápido'],
    ingredients: [
      { name: 'Lechuga romana', amount: '1 planta' },
      { name: 'Queso parmesano rallado', amount: '40g' },
      { name: 'Pan de molde', amount: '2 rebanadas' },
      { name: 'Mayonesa', amount: '3 cdas' },
      { name: 'Limón', amount: '½ unidad' },
      { name: 'Ajo', amount: '1 diente' },
      { name: 'Mostaza', amount: '1 cdta' },
    ],
    steps: [
      { order: 1, description: 'Cortás el pan en cubos y los tostás en horno o sartén con aceite de oliva hasta dorar.' },
      { order: 2, description: 'Mezclás mayonesa, jugo de limón, ajo rallado y mostaza hasta formar el aderezo.' },
      { order: 3, description: 'Lavás y secás bien la lechuga. La cortás en trozos medianos.' },
      { order: 4, description: 'Mezclás la lechuga con el aderezo hasta cubrir bien las hojas.' },
      { order: 5, description: 'Agregás crutones y parmesano. Servís inmediatamente.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Tacos de Pollo',
    description: 'Tacos jugosos con pollo especiado, pico de gallo fresco y crema. Una cena rápida con mucho sabor.',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    category: 'Cena', difficulty: 'Fácil', cookTime: '25 min', servings: 3,
    rating: 4.7, reviewCount: 315,
    tags: ['cena', 'tacos', 'pollo', 'mexicano', 'rápido'],
    ingredients: [
      { name: 'Pechuga de pollo', amount: '400g' },
      { name: 'Tortillas de trigo', amount: '6 unidades' },
      { name: 'Tomate', amount: '1 unidad' },
      { name: 'Cebolla morada', amount: '½ unidad' },
      { name: 'Cilantro', amount: '1 puñado' },
      { name: 'Limón', amount: '1 unidad' },
      { name: 'Pimentón ahumado', amount: '1 cdta' },
      { name: 'Comino', amount: '½ cdta' },
    ],
    steps: [
      { order: 1, description: 'Condimentás el pollo con pimentón, comino, sal y pimienta.' },
      { order: 2, description: 'Lo cocinás en sartén con aceite a fuego medio-alto, 5-6 minutos por lado.' },
      { order: 3, description: 'Lo dejás reposar 5 minutos y lo cortás en tiras.' },
      { order: 4, description: 'Preparás el pico de gallo: tomate, cebolla y cilantro picados con jugo de limón y sal.' },
      { order: 5, description: 'Calentás las tortillas y armás los tacos con el pollo y el pico de gallo.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Bizcochuelo de Naranja',
    description: 'Un budín húmedo y esponjoso con aroma a naranja. Perfecto para la merienda o para llevar a cualquier lado.',
    imageUrl: 'https://images.unsplash.com/photo-1587668178277-295251f900ce?w=800',
    category: 'Postre', difficulty: 'Fácil', cookTime: '50 min', servings: 8,
    rating: 4.7, reviewCount: 178,
    tags: ['postre', 'naranja', 'bizcochuelo', 'merienda', 'horno'],
    ingredients: [
      { name: 'Harina', amount: '2 tazas' },
      { name: 'Azúcar', amount: '1 taza' },
      { name: 'Huevos', amount: '3 unidades' },
      { name: 'Aceite', amount: '½ taza' },
      { name: 'Jugo de naranja', amount: '½ taza' },
      { name: 'Ralladura de naranja', amount: '1 naranja' },
      { name: 'Polvo de hornear', amount: '2 cdtas' },
    ],
    steps: [
      { order: 1, description: 'Precalentás el horno a 180°C. Engrasás y enharinás un molde.' },
      { order: 2, description: 'Batís los huevos con el azúcar hasta blanquear. Agregás el aceite y el jugo de naranja.' },
      { order: 3, description: 'Incorporás la ralladura de naranja.' },
      { order: 4, description: 'Tamizás la harina con el polvo de hornear y la integrás a la mezcla con movimientos suaves.' },
      { order: 5, description: 'Volcás en el molde y horneás 40-45 minutos. Pinchás con un palillo para verificar la cocción.' },
    ],
  },

  // ── 30 recetas nuevas ──────────────────────────────────────────────────
  {
    author: 'sofia',
    title: 'Tostadas con Ricotta y Miel',
    description: 'Tostadas crocantes con ricotta cremosa, miel y nueces. Un desayuno dulce y rápido.',
    imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800',
    category: 'Desayuno', difficulty: 'Fácil', cookTime: '10 min', servings: 2,
    rating: 4.6, reviewCount: 124,
    tags: ['desayuno', 'ricotta', 'miel', 'rápido'],
    ingredients: [
      { name: 'Pan integral', amount: '4 rebanadas' },
      { name: 'Ricotta', amount: '200g' },
      { name: 'Miel', amount: '3 cdas' },
      { name: 'Nueces picadas', amount: '¼ taza' },
      { name: 'Canela', amount: '1 pizca' },
    ],
    steps: [
      { order: 1, description: 'Tostás el pan hasta que esté dorado.' },
      { order: 2, description: 'Untás generosamente con ricotta.' },
      { order: 3, description: 'Rociás con miel y espolvoreás nueces y canela.' },
    ],
  },
  {
    author: 'marco',
    title: 'Huevos Revueltos con Espinaca',
    description: 'Huevos cremosos salteados con espinaca fresca y queso. Proteína y verdura en un solo plato.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    category: 'Desayuno', difficulty: 'Fácil', cookTime: '12 min', servings: 2,
    rating: 4.5, reviewCount: 98,
    tags: ['desayuno', 'huevos', 'espinaca', 'saludable'],
    ingredients: [
      { name: 'Huevos', amount: '4 unidades' },
      { name: 'Espinaca fresca', amount: '2 tazas' },
      { name: 'Queso rallado', amount: '30g' },
      { name: 'Manteca', amount: '1 cda' },
      { name: 'Sal y pimienta', amount: 'Al gusto' },
    ],
    steps: [
      { order: 1, description: 'Salteás la espinaca en manteca hasta que se reduzca.' },
      { order: 2, description: 'Batís los huevos y los agregás a la sartén a fuego bajo.' },
      { order: 3, description: 'Revolvés constantemente hasta que cuajen suavemente.' },
      { order: 4, description: 'Agregás el queso, salpimentás y servís enseguida.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Smoothie Bowl de Frutillas',
    description: 'Un bowl espeso y refrescante de frutillas congeladas, banana y toppings crocantes.',
    imageUrl: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=800',
    category: 'Desayuno', difficulty: 'Fácil', cookTime: '10 min', servings: 1,
    rating: 4.7, reviewCount: 145,
    tags: ['desayuno', 'smoothie', 'frutillas', 'saludable', 'sin horno'],
    ingredients: [
      { name: 'Frutillas congeladas', amount: '1 ½ tazas' },
      { name: 'Banana', amount: '1 unidad' },
      { name: 'Yogur natural', amount: '½ taza' },
      { name: 'Granola', amount: '¼ taza' },
      { name: 'Semillas de chía', amount: '1 cdta' },
    ],
    steps: [
      { order: 1, description: 'Licuás las frutillas, la banana y el yogur hasta lograr una textura espesa.' },
      { order: 2, description: 'Servís en un bowl.' },
      { order: 3, description: 'Decorás con granola, semillas de chía y fruta fresca a gusto.' },
    ],
  },
  {
    author: 'marco',
    title: 'Omelette de Queso y Jamón',
    description: 'El clásico omelette francés, esponjoso por fuera y con el relleno justo de queso y jamón.',
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800',
    category: 'Desayuno', difficulty: 'Fácil', cookTime: '10 min', servings: 1,
    rating: 4.4, reviewCount: 76,
    tags: ['desayuno', 'omelette', 'huevos', 'rápido'],
    ingredients: [
      { name: 'Huevos', amount: '3 unidades' },
      { name: 'Jamón', amount: '2 fetas' },
      { name: 'Queso de máquina', amount: '2 fetas' },
      { name: 'Manteca', amount: '1 cda' },
      { name: 'Sal y pimienta', amount: 'Al gusto' },
    ],
    steps: [
      { order: 1, description: 'Batís los huevos con sal y pimienta.' },
      { order: 2, description: 'Volcás en sartén caliente con manteca y cocinás a fuego medio.' },
      { order: 3, description: 'Cuando empieza a cuajar, agregás el jamón y el queso de un lado.' },
      { order: 4, description: 'Doblás por la mitad y cocinás 1 minuto más antes de servir.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Yogur con Granola Casera',
    description: 'Capas de yogur natural, granola tostada con miel y frutas de estación.',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800',
    category: 'Desayuno', difficulty: 'Fácil', cookTime: '15 min', servings: 2,
    rating: 4.6, reviewCount: 110,
    tags: ['desayuno', 'yogur', 'granola', 'saludable'],
    ingredients: [
      { name: 'Yogur natural', amount: '2 tazas' },
      { name: 'Avena', amount: '1 taza' },
      { name: 'Miel', amount: '3 cdas' },
      { name: 'Almendras', amount: '¼ taza' },
      { name: 'Fruta de estación', amount: 'A gusto' },
    ],
    steps: [
      { order: 1, description: 'Mezclás la avena con la miel y las almendras, horneás 10 minutos a 180°C hasta dorar.' },
      { order: 2, description: 'Dejás enfriar la granola.' },
      { order: 3, description: 'Armás capas de yogur, granola y fruta en un vaso o bowl.' },
    ],
  },
  {
    author: 'marco',
    title: 'Wok de Vegetales y Tofu',
    description: 'Un salteado rápido de vegetales crocantes y tofu dorado con salsa de soja.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
    category: 'Almuerzo', difficulty: 'Medio', cookTime: '25 min', servings: 2,
    rating: 4.5, reviewCount: 87,
    tags: ['almuerzo', 'vegetariano', 'tofu', 'wok', 'asiático'],
    ingredients: [
      { name: 'Tofu firme', amount: '300g' },
      { name: 'Brócoli', amount: '1 taza' },
      { name: 'Zanahoria', amount: '1 unidad' },
      { name: 'Pimiento rojo', amount: '1 unidad' },
      { name: 'Salsa de soja', amount: '3 cdas' },
      { name: 'Jengibre', amount: '1 cdta' },
      { name: 'Aceite de sésamo', amount: '1 cda' },
    ],
    steps: [
      { order: 1, description: 'Cortás el tofu en cubos y lo dorás en sartén con un poco de aceite.' },
      { order: 2, description: 'Retirás el tofu y en la misma sartén salteás los vegetales a fuego fuerte.' },
      { order: 3, description: 'Agregás el jengibre, la salsa de soja y el tofu de vuelta.' },
      { order: 4, description: 'Salteás todo junto 2-3 minutos y servís con aceite de sésamo por encima.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Milanesa con Puré',
    description: 'Milanesas crocantes de ternera con un puré de papas cremoso. El clásico de toda la vida.',
    imageUrl: 'https://images.unsplash.com/photo-1432139509613-5c4255815697?w=800',
    category: 'Almuerzo', difficulty: 'Medio', cookTime: '40 min', servings: 4,
    rating: 4.8, reviewCount: 267,
    tags: ['almuerzo', 'milanesa', 'puré', 'clásico'],
    ingredients: [
      { name: 'Milanesas de ternera', amount: '4 unidades' },
      { name: 'Pan rallado', amount: '1 taza' },
      { name: 'Huevos', amount: '2 unidades' },
      { name: 'Papas', amount: '1kg' },
      { name: 'Leche', amount: '½ taza' },
      { name: 'Manteca', amount: '50g' },
    ],
    steps: [
      { order: 1, description: 'Pasás las milanesas por huevo batido y después por pan rallado.' },
      { order: 2, description: 'Freís en aceite caliente hasta dorar de ambos lados.' },
      { order: 3, description: 'Hervís las papas hasta que estén tiernas y las hacés puré con leche y manteca.' },
      { order: 4, description: 'Servís las milanesas calientes acompañadas del puré.' },
    ],
  },
  {
    author: 'marco',
    title: 'Risotto de Hongos',
    description: 'Un risotto cremoso y untuoso con hongos salteados y parmesano. Comfort food italiano.',
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800',
    category: 'Almuerzo', difficulty: 'Medio', cookTime: '35 min', servings: 3,
    rating: 4.7, reviewCount: 189,
    tags: ['almuerzo', 'risotto', 'hongos', 'italiana'],
    ingredients: [
      { name: 'Arroz arborio', amount: '300g' },
      { name: 'Hongos de pino', amount: '250g' },
      { name: 'Caldo de verduras', amount: '1L' },
      { name: 'Vino blanco', amount: '½ taza' },
      { name: 'Cebolla', amount: '1 unidad' },
      { name: 'Queso parmesano', amount: '50g' },
      { name: 'Manteca', amount: '2 cdas' },
    ],
    steps: [
      { order: 1, description: 'Salteás la cebolla picada en manteca hasta transparentar.' },
      { order: 2, description: 'Agregás el arroz y lo nacarás 2 minutos. Vertís el vino y dejás evaporar.' },
      { order: 3, description: 'Incorporás el caldo de a poco, revolviendo constantemente hasta que el arroz esté cremoso.' },
      { order: 4, description: 'Salteás los hongos aparte y los incorporás al final junto con el parmesano.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Empanadas de Carne',
    description: 'Empanadas jugosas de carne cortada a cuchillo, al estilo criollo, horneadas hasta dorar.',
    imageUrl: 'https://images.unsplash.com/photo-1604467707321-7e167bb8d72c?w=800',
    category: 'Almuerzo', difficulty: 'Medio', cookTime: '1 hora', servings: 6,
    rating: 4.9, reviewCount: 412,
    tags: ['almuerzo', 'empanadas', 'carne', 'criollo'],
    ingredients: [
      { name: 'Tapas de empanada', amount: '12 unidades' },
      { name: 'Carne picada a cuchillo', amount: '500g' },
      { name: 'Cebolla', amount: '2 unidades' },
      { name: 'Huevos duros', amount: '2 unidades' },
      { name: 'Aceitunas', amount: '12 unidades' },
      { name: 'Pimentón y comino', amount: '1 cdta c/u' },
    ],
    steps: [
      { order: 1, description: 'Salteás la cebolla hasta transparentar y agregás la carne con las especias.' },
      { order: 2, description: 'Cocinás hasta que la carne esté en su punto y dejás enfriar.' },
      { order: 3, description: 'Agregás huevo duro picado y aceitunas al relleno frío.' },
      { order: 4, description: 'Rellenás las tapas, cerrás con repulgue y horneás 20 minutos a 200°C.' },
    ],
  },
  {
    author: 'marco',
    title: 'Sándwich de Pollo Grillado',
    description: 'Pan ciabatta con pollo grillado, vegetales frescos y alioli casero.',
    imageUrl: 'https://images.unsplash.com/photo-1521390188846-e2a3a97453ca?w=800',
    category: 'Almuerzo', difficulty: 'Fácil', cookTime: '20 min', servings: 2,
    rating: 4.5, reviewCount: 93,
    tags: ['almuerzo', 'sándwich', 'pollo', 'rápido'],
    ingredients: [
      { name: 'Pechuga de pollo', amount: '2 unidades' },
      { name: 'Pan ciabatta', amount: '2 unidades' },
      { name: 'Lechuga', amount: '4 hojas' },
      { name: 'Tomate', amount: '1 unidad' },
      { name: 'Mayonesa', amount: '3 cdas' },
      { name: 'Ajo', amount: '1 diente' },
    ],
    steps: [
      { order: 1, description: 'Condimentás y grillás el pollo hasta que esté bien cocido.' },
      { order: 2, description: 'Mezclás mayonesa con ajo rallado para el alioli.' },
      { order: 3, description: 'Tostás el pan y armás el sándwich con alioli, pollo, lechuga y tomate.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Salmón al Horno con Espárragos',
    description: 'Filetes de salmón jugosos al horno con espárragos y limón. Liviano y elegante.',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    category: 'Cena', difficulty: 'Fácil', cookTime: '25 min', servings: 2,
    rating: 4.8, reviewCount: 156,
    tags: ['cena', 'salmón', 'saludable', 'horno'],
    ingredients: [
      { name: 'Filetes de salmón', amount: '2 unidades' },
      { name: 'Espárragos', amount: '1 atado' },
      { name: 'Limón', amount: '1 unidad' },
      { name: 'Aceite de oliva', amount: '2 cdas' },
      { name: 'Ajo', amount: '2 dientes' },
      { name: 'Sal y pimienta', amount: 'Al gusto' },
    ],
    steps: [
      { order: 1, description: 'Precalentás el horno a 200°C.' },
      { order: 2, description: 'Colocás el salmón y los espárragos en una fuente, condimentás con ajo, aceite, sal y pimienta.' },
      { order: 3, description: 'Horneás 15-18 minutos hasta que el salmón esté cocido.' },
      { order: 4, description: 'Servís con rodajas de limón fresco por encima.' },
    ],
  },
  {
    author: 'marco',
    title: 'Pizza Casera Margherita',
    description: 'La pizza clásica italiana: masa fina, salsa de tomate, mozzarella fresca y albahaca.',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    category: 'Cena', difficulty: 'Medio', cookTime: '50 min', servings: 4,
    rating: 4.9, reviewCount: 387,
    tags: ['cena', 'pizza', 'italiana', 'clásica'],
    ingredients: [
      { name: 'Harina', amount: '500g' },
      { name: 'Levadura seca', amount: '7g' },
      { name: 'Salsa de tomate', amount: '1 taza' },
      { name: 'Mozzarella fresca', amount: '250g' },
      { name: 'Albahaca fresca', amount: 'Un puñado' },
      { name: 'Aceite de oliva', amount: '3 cdas' },
    ],
    steps: [
      { order: 1, description: 'Preparás la masa con harina, levadura, agua tibia y sal. Dejás levar 1 hora.' },
      { order: 2, description: 'Estirás la masa fina y la colocás en una bandeja.' },
      { order: 3, description: 'Cubrís con salsa de tomate y mozzarella en trozos.' },
      { order: 4, description: 'Horneás a máxima temperatura 10-12 minutos hasta dorar los bordes.' },
      { order: 5, description: 'Decorás con albahaca fresca y un chorrito de aceite de oliva al salir del horno.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Hamburguesas Caseras',
    description: 'Hamburguesas jugosas de carne, con queso cheddar derretido y vegetales frescos.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    category: 'Cena', difficulty: 'Fácil', cookTime: '25 min', servings: 4,
    rating: 4.7, reviewCount: 234,
    tags: ['cena', 'hamburguesa', 'carne', 'rápido'],
    ingredients: [
      { name: 'Carne picada', amount: '600g' },
      { name: 'Pan de hamburguesa', amount: '4 unidades' },
      { name: 'Queso cheddar', amount: '4 fetas' },
      { name: 'Lechuga', amount: '4 hojas' },
      { name: 'Tomate', amount: '1 unidad' },
      { name: 'Cebolla morada', amount: '½ unidad' },
    ],
    steps: [
      { order: 1, description: 'Formás 4 medallones con la carne, salpimentás.' },
      { order: 2, description: 'Cocinás en plancha o sartén caliente 4 minutos por lado.' },
      { order: 3, description: 'Agregás el queso en el último minuto para que se derrita.' },
      { order: 4, description: 'Tostás el pan y armás la hamburguesa con lechuga, tomate y cebolla.' },
    ],
  },
  {
    author: 'marco',
    title: 'Curry de Garbanzos',
    description: 'Un curry cremoso y especiado de garbanzos en salsa de tomate y leche de coco.',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    category: 'Cena', difficulty: 'Fácil', cookTime: '30 min', servings: 3,
    rating: 4.6, reviewCount: 142,
    tags: ['cena', 'vegetariano', 'curry', 'garbanzos', 'indio'],
    ingredients: [
      { name: 'Garbanzos cocidos', amount: '2 latas' },
      { name: 'Leche de coco', amount: '400ml' },
      { name: 'Tomate triturado', amount: '1 taza' },
      { name: 'Cebolla', amount: '1 unidad' },
      { name: 'Curry en polvo', amount: '2 cdas' },
      { name: 'Jengibre', amount: '1 cdta' },
      { name: 'Ajo', amount: '2 dientes' },
    ],
    steps: [
      { order: 1, description: 'Salteás cebolla, ajo y jengibre hasta que estén dorados.' },
      { order: 2, description: 'Agregás el curry en polvo y cocinás 1 minuto para que libere aroma.' },
      { order: 3, description: 'Incorporás el tomate triturado y la leche de coco, cocinás 10 minutos.' },
      { order: 4, description: 'Agregás los garbanzos y cocinás 10 minutos más a fuego bajo. Servís con arroz.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Pollo al Limón con Papas',
    description: 'Pollo al horno marinado en limón y hierbas, con papas doradas en la misma fuente.',
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800',
    category: 'Cena', difficulty: 'Fácil', cookTime: '1 hora', servings: 4,
    rating: 4.7, reviewCount: 198,
    tags: ['cena', 'pollo', 'limón', 'horno'],
    ingredients: [
      { name: 'Muslos de pollo', amount: '6 unidades' },
      { name: 'Papas', amount: '4 unidades' },
      { name: 'Limón', amount: '2 unidades' },
      { name: 'Romero fresco', amount: '2 ramitas' },
      { name: 'Ajo', amount: '4 dientes' },
      { name: 'Aceite de oliva', amount: '3 cdas' },
    ],
    steps: [
      { order: 1, description: 'Marinás el pollo con jugo de limón, ajo, romero, aceite, sal y pimienta por 20 minutos.' },
      { order: 2, description: 'Cortás las papas en gajos y las colocás en la fuente junto al pollo.' },
      { order: 3, description: 'Horneás a 200°C por 45-50 minutos hasta que el pollo esté dorado y las papas tiernas.' },
    ],
  },
  {
    author: 'marco',
    title: 'Flan Casero',
    description: 'El postre de toda la vida: flan suave con caramelo, hecho con pocos ingredientes.',
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
    category: 'Postre', difficulty: 'Medio', cookTime: '1 hora', servings: 6,
    rating: 4.8, reviewCount: 256,
    tags: ['postre', 'flan', 'clásico', 'horno'],
    ingredients: [
      { name: 'Leche', amount: '1L' },
      { name: 'Huevos', amount: '6 unidades' },
      { name: 'Azúcar', amount: '1 taza' },
      { name: 'Esencia de vainilla', amount: '1 cdta' },
      { name: 'Azúcar para el caramelo', amount: '½ taza' },
    ],
    steps: [
      { order: 1, description: 'Preparás un caramelo dorando el azúcar en una flanera, cubrís el fondo.' },
      { order: 2, description: 'Batís los huevos con el azúcar, agregás la leche tibia y la vainilla.' },
      { order: 3, description: 'Volcás la mezcla en la flanera y cocinás a baño maría en el horno 45 minutos a 180°C.' },
      { order: 4, description: 'Dejás enfriar y refrigerás antes de desmoldar.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Brownies de Chocolate',
    description: 'Brownies húmedos y densos, con una capa crocante arriba y mucho chocolate.',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800',
    category: 'Postre', difficulty: 'Fácil', cookTime: '40 min', servings: 9,
    rating: 4.9, reviewCount: 301,
    tags: ['postre', 'chocolate', 'brownies', 'horno'],
    ingredients: [
      { name: 'Chocolate negro', amount: '200g' },
      { name: 'Manteca', amount: '150g' },
      { name: 'Azúcar', amount: '1 ½ tazas' },
      { name: 'Huevos', amount: '3 unidades' },
      { name: 'Harina', amount: '1 taza' },
      { name: 'Cacao amargo', amount: '¼ taza' },
    ],
    steps: [
      { order: 1, description: 'Derretís el chocolate con la manteca a baño maría.' },
      { order: 2, description: 'Batís los huevos con el azúcar e incorporás el chocolate tibio.' },
      { order: 3, description: 'Agregás la harina tamizada con el cacao, mezclás sin batir de más.' },
      { order: 4, description: 'Horneás en molde cuadrado a 180°C por 25-30 minutos. El centro debe quedar húmedo.' },
    ],
  },
  {
    author: 'marco',
    title: 'Tarta de Manzana',
    description: 'Tarta clásica con base crocante y manzanas caramelizadas con canela.',
    imageUrl: 'https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=800',
    category: 'Postre', difficulty: 'Medio', cookTime: '1 hora', servings: 8,
    rating: 4.7, reviewCount: 167,
    tags: ['postre', 'manzana', 'tarta', 'horno'],
    ingredients: [
      { name: 'Masa para tarta', amount: '1 disco' },
      { name: 'Manzanas', amount: '5 unidades' },
      { name: 'Azúcar', amount: '½ taza' },
      { name: 'Canela', amount: '1 cdta' },
      { name: 'Manteca', amount: '30g' },
      { name: 'Mermelada de damasco', amount: '2 cdas' },
    ],
    steps: [
      { order: 1, description: 'Forrás un molde con la masa y la pinchás con un tenedor.' },
      { order: 2, description: 'Cortás las manzanas en láminas finas y las mezclás con azúcar y canela.' },
      { order: 3, description: 'Acomodás las manzanas en forma de abanico sobre la masa, agregás trocitos de manteca.' },
      { order: 4, description: 'Horneás a 180°C por 40 minutos. Al salir, pintás con mermelada tibia para dar brillo.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Helado de Vainilla Casero',
    description: 'Helado cremoso de vainilla, sin máquina, solo con crema y leche condensada.',
    imageUrl: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=800',
    category: 'Postre', difficulty: 'Fácil', cookTime: '20 min', servings: 6,
    rating: 4.6, reviewCount: 134,
    tags: ['postre', 'helado', 'sin horno', 'vainilla'],
    ingredients: [
      { name: 'Crema de leche', amount: '500ml' },
      { name: 'Leche condensada', amount: '1 lata' },
      { name: 'Esencia de vainilla', amount: '1 cda' },
    ],
    steps: [
      { order: 1, description: 'Batís la crema a punto chantilly bien firme.' },
      { order: 2, description: 'Incorporás la leche condensada y la vainilla con movimientos envolventes.' },
      { order: 3, description: 'Volcás en un molde y congelás mínimo 6 horas antes de servir.' },
    ],
  },
  {
    author: 'marco',
    title: 'Alfajores de Maicena',
    description: 'Alfajores tiernos que se deshacen en la boca, rellenos de dulce de leche y coco rallado.',
    imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583a?w=800',
    category: 'Postre', difficulty: 'Medio', cookTime: '45 min', servings: 12,
    rating: 4.8, reviewCount: 223,
    tags: ['postre', 'alfajores', 'dulce de leche', 'horno'],
    ingredients: [
      { name: 'Maicena', amount: '2 tazas' },
      { name: 'Harina', amount: '½ taza' },
      { name: 'Manteca', amount: '150g' },
      { name: 'Azúcar', amount: '½ taza' },
      { name: 'Yemas', amount: '2 unidades' },
      { name: 'Dulce de leche', amount: '1 taza' },
      { name: 'Coco rallado', amount: '1 taza' },
    ],
    steps: [
      { order: 1, description: 'Mezclás la manteca con el azúcar hasta cremar. Agregás las yemas.' },
      { order: 2, description: 'Incorporás la maicena y harina tamizadas hasta formar una masa tierna.' },
      { order: 3, description: 'Estirás y cortás círculos. Horneás a 180°C por 10-12 minutos sin dorar.' },
      { order: 4, description: 'Una vez fríos, unís de a pares con dulce de leche y pasás los bordes por coco rallado.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Hummus con Bastones de Verdura',
    description: 'Hummus cremoso de garbanzos con tahini, ideal para untar con vegetales frescos.',
    imageUrl: 'https://images.unsplash.com/photo-1571197119282-7c4e2b9d7f73?w=800',
    category: 'Snack', difficulty: 'Fácil', cookTime: '10 min', servings: 4,
    rating: 4.5, reviewCount: 102,
    tags: ['snack', 'hummus', 'vegetariano', 'saludable', 'sin horno'],
    ingredients: [
      { name: 'Garbanzos cocidos', amount: '2 tazas' },
      { name: 'Tahini', amount: '3 cdas' },
      { name: 'Limón', amount: '1 unidad' },
      { name: 'Ajo', amount: '1 diente' },
      { name: 'Aceite de oliva', amount: '3 cdas' },
      { name: 'Zanahoria y apio', amount: 'Para acompañar' },
    ],
    steps: [
      { order: 1, description: 'Procesás los garbanzos con tahini, jugo de limón y ajo hasta lograr una pasta suave.' },
      { order: 2, description: 'Agregás aceite de oliva de a poco mientras procesás hasta la consistencia deseada.' },
      { order: 3, description: 'Servís con un chorrito de aceite por encima y bastones de verdura.' },
    ],
  },
  {
    author: 'marco',
    title: 'Palomitas Caseras',
    description: 'Pop corn esponjoso hecho en sartén, con manteca y un toque de sal.',
    imageUrl: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=800',
    category: 'Snack', difficulty: 'Fácil', cookTime: '10 min', servings: 4,
    rating: 4.3, reviewCount: 67,
    tags: ['snack', 'palomitas', 'rápido'],
    ingredients: [
      { name: 'Maíz pisingallo', amount: '½ taza' },
      { name: 'Aceite', amount: '2 cdas' },
      { name: 'Manteca', amount: '2 cdas' },
      { name: 'Sal', amount: 'Al gusto' },
    ],
    steps: [
      { order: 1, description: 'Calentás el aceite en una olla con tapa a fuego medio-alto.' },
      { order: 2, description: 'Agregás el maíz, tapás y esperás a que empiece a explotar, agitando de vez en cuando.' },
      { order: 3, description: 'Una vez que dejan de explotar, retirás del fuego, agregás manteca derretida y sal.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Barras de Cereal',
    description: 'Barras energéticas caseras con avena, miel y frutos secos, perfectas para llevar.',
    imageUrl: 'https://images.unsplash.com/photo-1571748982800-fa51082c2224?w=800',
    category: 'Snack', difficulty: 'Fácil', cookTime: '30 min', servings: 8,
    rating: 4.4, reviewCount: 81,
    tags: ['snack', 'avena', 'saludable', 'horno'],
    ingredients: [
      { name: 'Avena', amount: '2 tazas' },
      { name: 'Miel', amount: '½ taza' },
      { name: 'Manteca de maní', amount: '¼ taza' },
      { name: 'Pasas de uva', amount: '½ taza' },
      { name: 'Nueces picadas', amount: '½ taza' },
    ],
    steps: [
      { order: 1, description: 'Calentás la miel con la manteca de maní hasta que estén bien integradas.' },
      { order: 2, description: 'Mezclás con la avena, pasas y nueces hasta que todo quede húmedo.' },
      { order: 3, description: 'Presionás firme en una fuente y horneás a 160°C por 20 minutos.' },
      { order: 4, description: 'Dejás enfriar por completo antes de cortar en barras.' },
    ],
  },
  {
    author: 'marco',
    title: 'Guacamole con Nachos',
    description: 'Guacamole fresco de palta, tomate y cilantro, acompañado de nachos crocantes.',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800',
    category: 'Snack', difficulty: 'Fácil', cookTime: '10 min', servings: 4,
    rating: 4.6, reviewCount: 119,
    tags: ['snack', 'guacamole', 'mexicano', 'sin horno'],
    ingredients: [
      { name: 'Paltas maduras', amount: '3 unidades' },
      { name: 'Tomate', amount: '1 unidad' },
      { name: 'Cebolla morada', amount: '¼ unidad' },
      { name: 'Cilantro', amount: 'Un puñado' },
      { name: 'Limón', amount: '1 unidad' },
      { name: 'Nachos', amount: '1 paquete' },
    ],
    steps: [
      { order: 1, description: 'Aplastás las paltas con un tenedor dejando un poco de textura.' },
      { order: 2, description: 'Agregás tomate, cebolla y cilantro picados finamente.' },
      { order: 3, description: 'Condimentás con jugo de limón y sal. Servís enseguida con nachos.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Bruschettas de Tomate',
    description: 'Pan tostado con tomate fresco, albahaca y ajo. Un clásico aperitivo italiano.',
    imageUrl: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800',
    category: 'Snack', difficulty: 'Fácil', cookTime: '15 min', servings: 4,
    rating: 4.5, reviewCount: 95,
    tags: ['snack', 'bruschetta', 'tomate', 'italiana', 'rápido'],
    ingredients: [
      { name: 'Pan baguette', amount: '1 unidad' },
      { name: 'Tomates', amount: '4 unidades' },
      { name: 'Albahaca fresca', amount: 'Un puñado' },
      { name: 'Ajo', amount: '1 diente' },
      { name: 'Aceite de oliva', amount: '3 cdas' },
    ],
    steps: [
      { order: 1, description: 'Cortás el pan en rebanadas y las tostás hasta dorar.' },
      { order: 2, description: 'Frotás cada tostada con el diente de ajo cortado.' },
      { order: 3, description: 'Picás el tomate y la albahaca, mezclás con aceite de oliva y sal.' },
      { order: 4, description: 'Cubrís cada tostada con la mezcla de tomate justo antes de servir.' },
    ],
  },
  {
    author: 'marco',
    title: 'Berenjenas a la Parmesana',
    description: 'Capas de berenjena, salsa de tomate y mozzarella gratinada al horno.',
    imageUrl: 'https://images.unsplash.com/photo-1572441713132-51c75654db73?w=800',
    category: 'Vegetariano', difficulty: 'Medio', cookTime: '50 min', servings: 4,
    rating: 4.7, reviewCount: 138,
    tags: ['vegetariano', 'berenjena', 'horno', 'italiana'],
    ingredients: [
      { name: 'Berenjenas', amount: '2 unidades' },
      { name: 'Salsa de tomate', amount: '2 tazas' },
      { name: 'Mozzarella', amount: '200g' },
      { name: 'Queso parmesano', amount: '50g' },
      { name: 'Albahaca fresca', amount: 'Un puñado' },
    ],
    steps: [
      { order: 1, description: 'Cortás las berenjenas en láminas, las salás y dejás reposar 15 minutos para que suelten amargor.' },
      { order: 2, description: 'Las grillás o doras en sartén con un poco de aceite.' },
      { order: 3, description: 'Armás capas en una fuente: berenjena, salsa de tomate, mozzarella, repetís.' },
      { order: 4, description: 'Cubrís con parmesano y horneás a 190°C por 25 minutos hasta gratinar.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Tarta de Acelga',
    description: 'Tarta clásica de acelga y queso, con masa casera crocante.',
    imageUrl: 'https://images.unsplash.com/photo-1610440042657-612c34d95e9f?w=800',
    category: 'Vegetariano', difficulty: 'Fácil', cookTime: '50 min', servings: 6,
    rating: 4.5, reviewCount: 112,
    tags: ['vegetariano', 'tarta', 'acelga', 'horno'],
    ingredients: [
      { name: 'Masa para tarta', amount: '2 discos' },
      { name: 'Acelga', amount: '1 atado' },
      { name: 'Cebolla', amount: '1 unidad' },
      { name: 'Huevos', amount: '3 unidades' },
      { name: 'Queso rallado', amount: '100g' },
      { name: 'Crema de leche', amount: '½ taza' },
    ],
    steps: [
      { order: 1, description: 'Hervís la acelga, la escurrís bien y la picás.' },
      { order: 2, description: 'Salteás la cebolla y la mezclás con la acelga, huevos, queso y crema.' },
      { order: 3, description: 'Forrás un molde con una masa, rellenás y cubrís con la otra masa.' },
      { order: 4, description: 'Horneás a 190°C por 30-35 minutos hasta dorar.' },
    ],
  },
  {
    author: 'marco',
    title: 'Falafel con Salsa de Yogur',
    description: 'Bolitas crocantes de garbanzos especiados, con una salsa fresca de yogur y pepino.',
    imageUrl: 'https://images.unsplash.com/photo-1593001874117-c99c800e3eb6?w=800',
    category: 'Vegetariano', difficulty: 'Medio', cookTime: '40 min', servings: 4,
    rating: 4.6, reviewCount: 105,
    tags: ['vegetariano', 'falafel', 'garbanzos', 'medio oriente'],
    ingredients: [
      { name: 'Garbanzos remojados', amount: '2 tazas' },
      { name: 'Cebolla', amount: '½ unidad' },
      { name: 'Ajo', amount: '2 dientes' },
      { name: 'Comino y cilantro molido', amount: '1 cdta c/u' },
      { name: 'Yogur natural', amount: '1 taza' },
      { name: 'Pepino', amount: '½ unidad' },
    ],
    steps: [
      { order: 1, description: 'Procesás los garbanzos crudos remojados con cebolla, ajo y especias hasta lograr una pasta gruesa.' },
      { order: 2, description: 'Formás bolitas y las freís en aceite caliente hasta dorar parejo.' },
      { order: 3, description: 'Mezclás el yogur con pepino rallado, sal y un chorrito de limón para la salsa.' },
      { order: 4, description: 'Servís los falafel calientes con la salsa de yogur.' },
    ],
  },
  {
    author: 'sofia',
    title: 'Sopa de Calabaza',
    description: 'Una sopa cremosa y reconfortante de calabaza asada con un toque de jengibre.',
    imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800',
    category: 'Vegetariano', difficulty: 'Fácil', cookTime: '40 min', servings: 4,
    rating: 4.6, reviewCount: 128,
    tags: ['vegetariano', 'sopa', 'calabaza', 'saludable'],
    ingredients: [
      { name: 'Calabaza', amount: '1kg' },
      { name: 'Cebolla', amount: '1 unidad' },
      { name: 'Caldo de verduras', amount: '1L' },
      { name: 'Jengibre', amount: '1 cdta' },
      { name: 'Crema de leche', amount: '¼ taza' },
    ],
    steps: [
      { order: 1, description: 'Cortás la calabaza en cubos y la horneás 25 minutos hasta que esté tierna.' },
      { order: 2, description: 'Salteás la cebolla y el jengibre, agregás la calabaza horneada y el caldo.' },
      { order: 3, description: 'Cocinás 10 minutos y licuás hasta lograr una textura suave.' },
      { order: 4, description: 'Servís con un toque de crema por encima.' },
    ],
  },
  {
    author: 'marco',
    title: 'Lentejas Estofadas',
    description: 'Lentejas guisadas con vegetales, un plato abundante y nutritivo para el invierno.',
    imageUrl: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800',
    category: 'Vegetariano', difficulty: 'Fácil', cookTime: '45 min', servings: 4,
    rating: 4.5, reviewCount: 99,
    tags: ['vegetariano', 'lentejas', 'guiso', 'saludable'],
    ingredients: [
      { name: 'Lentejas', amount: '2 tazas' },
      { name: 'Zanahoria', amount: '2 unidades' },
      { name: 'Cebolla', amount: '1 unidad' },
      { name: 'Pimiento', amount: '1 unidad' },
      { name: 'Tomate triturado', amount: '1 taza' },
      { name: 'Pimentón ahumado', amount: '1 cdta' },
    ],
    steps: [
      { order: 1, description: 'Remojás las lentejas un par de horas si no son de cocción rápida.' },
      { order: 2, description: 'Salteás cebolla, zanahoria y pimiento picados hasta tiernizar.' },
      { order: 3, description: 'Agregás las lentejas, el tomate, el pimentón y agua hasta cubrir.' },
      { order: 4, description: 'Cocinás a fuego bajo 30-35 minutos hasta que las lentejas estén tiernas y el guiso espeso.' },
    ],
  },
];

async function upsertUser({ name, username, email, bio }) {
  const passwordHash = await bcrypt.hash(TEST_PASSWORD, 10);
  return prisma.user.upsert({
    where: { email },
    update: {},
    create: { name, username, email, bio, passwordHash },
  });
}

async function createRecipe(authorId, data) {
  const { ingredients, steps, author, ...rest } = data;
  return prisma.recipe.create({
    data: {
      ...rest,
      difficulty: difficultyToDb(rest.difficulty),
      authorId,
      ingredients: { create: ingredients },
      steps: { create: steps },
    },
  });
}

async function main() {
  const sofia = await upsertUser({
    name: 'Sofia Chen',
    username: 'sofía',
    email: 'sofia@sazon.app',
    bio: 'Cocinera apasionada 🍳 Comparto lo que cocino con amor.',
  });

  const marco = await upsertUser({
    name: 'Marco Rizzi',
    username: 'marco',
    email: 'marco@sazon.app',
    bio: 'Cocina italiana de toda la vida.',
  });

  const authorsByKey = { sofia: sofia.id, marco: marco.id };

  const createdRecipes = [];
  for (const recipeData of RECIPES) {
    const recipe = await createRecipe(authorsByKey[recipeData.author], recipeData);
    createdRecipes.push(recipe);
  }

  // Likes — Sofia (MOCK_USER) le dio like a sus dos primeras recetas, igual que en el mock del frontend
  await prisma.like.createMany({
    data: [
      { userId: sofia.id, recipeId: createdRecipes[0].id },
      { userId: sofia.id, recipeId: createdRecipes[1].id },
    ],
    skipDuplicates: true,
  });

  console.log(`Seed completado ✅ — ${createdRecipes.length} recetas creadas`);
  console.log(`Usuarios de prueba (password: "${TEST_PASSWORD}"):`);
  console.log('  sofia@sazon.app');
  console.log('  marco@sazon.app');
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
